server:
  port: 8888 # Config Server Default Port : 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/kakaocommerce/work/git-local-repo