server:
  port: 8888 # Config Server Default Port : 8888

spring:
  application:
    name: config-service
  profiles:
    active: native # Native File Repo 를 사용할 경우 설정
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
#      server:
#        native:
#          search-locations: file://${user.home}/work/native/file-repo # Native File Repo 를 사용할 경우 설정
        server:
          git:
            uri: https://github.com/ces518/spring-cloud-config-repository

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh # Actuator 를 활성화 시킬 End-Point 설정