server:
  port: 9001 # 포트를 0번으로 지정하면 가용가능한 범위 내에서 랜덤한 포트로 실행됨

spring:
  application:
    name: user-service

# Eureka 등록 및 외부 검색 허용 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka 서버 정보
